# Generated by Django 3.1.12 on 2025-10-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='threshold',
        ),
        migrations.AddField(
            model_name='device',
            name='auto_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_threshold_high',
            field=models.FloatField(default=28.0),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_threshold_low',
            field=models.FloatField(default=24.0),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('avg_temperature', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('fan_runtime_minutes', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('device_id', 'date')},
            },
        ),
    ]
